name: holbegram
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_database: ^10.2.0
  cloud_firestore: ^4.9.0 

  # Cloudinary pour l'upload d'image
  cloudinary_flutter: ^1.3.0

  # Gestion d'image
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Grille d'images (pour search.dart)
  flutter_staggered_grid_view: ^0.7.0

  # Utilitaires
  provider: ^6.1.5
  uuid: ^4.5.1
  pull_to_refresh: ^2.0.0
  http: ^1.4.0 

  #  Ajouté pour la barre de navigation en bas
  bottom_navy_bar: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: InstagramSans
      fonts:
        - asset: assets/fonts/InstagramSans.ttf
